### ISSUE TITLE
Google cloud project giving null when I try to refresh

### ISSUE THREAD

**Issue by Defalting** [GoogleCloudPlatform/iap-windows-rdc-plugin#53]
Hello,

I set up the project as a procedure and it worked for a few weeks. Then, when I needed to refresh the instances in the project, it gives me the following error

`System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Google.Solutions.CloudIap.Plugin.Integration.ComputeEngineAdapter.IsWindowsInstanceByGuestOsFeature(Instance instance)
   at Google.Solutions.CloudIap.Plugin.Gui.PluginEventHandler.<>c.<OnLoadServersClick>b__10_3(Instance i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Google.Solutions.CloudIap.Plugin.Gui.PluginEventHandler.<>c__DisplayClass10_0.<OnLoadServersClick>b__2(IEnumerable`1 allInstances)
   at Google.Solutions.CloudIap.Plugin.Gui.WaitDialog.<>c__DisplayClass13_2`1.<Run>b__1()`

I honestly have no idea what is causing this, so if you could explain it I would appreciate it.

**Comment by jpassing** [comment]
The fix is part of https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.47. Please let me know in case the problem persists.
